services:
  api:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: /src
          target: /app
        - action: rebuild
          path: ./pyproject.toml
    networks:
      - agent_network
    environment:
      - HF_TOKEN=hey
    volumes:
      - .:/app

networks:
    agent_network:
        driver: bridge
